# permissions for end users to edit jupyterkerneltemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jupyterkerneltemplate-editor-role
rules:
- apiGroups:
  - kubeflow.tkestack.io
  resources:
  - jupyterkerneltemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeflow.tkestack.io
  resources:
  - jupyterkerneltemplates/status
  verbs:
  - get
